#!/bin/bash
set -e

usage() { echo 'usage: github-split <repository> <file> [file] ...'; exit; }

log()   { echo -e "\e[30;47m ${1^^} \e[0m ${@:2}"; }
info()  { echo -e "\e[48;5;28m ${1^^} \e[0m ${@:2}"; }
warn()  { echo -e "\e[48;5;202m ${1^^} \e[0m ${@:2}" >&2; }
error() { echo -e "\e[48;5;196m ${1^^} \e[0m ${@:2}" >&2; }

[[ $1 == '-h' || $1 == '--help' || $# -lt 2 || ! -f $2 ]] && { usage; }

info create split
[[ -d split-$1 ]] && { error abort split-$1 already exists; exit; }

CWD=$(pwd)
TEMP=$(mktemp --directory)

log zip create archive.zip
zip --junk-paths -9 $TEMP/archive.zip "${@:2}"

cd $TEMP
MD5=$(md5sum archive.zip | cut -d ' ' -f 1)
log md5 $MD5

# filenames in the zip in base64
CONTENT=$(unzip -l archive.zip \
    | tail -n +4 \
    | head -n -2 \
    | sed --expression 's|^.*:[0-9]*\s*||' \
    | base64 -w 0)
    
SIZE=$(du archive.zip | sed 's|[^0-9].*$||g')
BYTES=500KB
[[ $SIZE -gt 5120 ]] && BYTES=1MB;
[[ $SIZE -gt 10240 ]] && BYTES=2MB; 
[[ $SIZE -gt 15360 ]] && BYTES=3MB;
[[ $SIZE -gt 20480 ]] && BYTES=4MB;
[[ $SIZE -gt 25600 ]] && BYTES=5MB;

log split archive.zip into pieces of $BYTES
split --bytes=$BYTES archive.zip
rm archive.zip
FILES=$(ls -1 | tr '\n' ' ')
FILES=${FILES::-1}

log create README.md
sed "s|{{REPOSITORY}}|$1|" \
    ~/.config/github-split/README.md.tpl \
    > README.md

log create install.sh
sed --expression "s|{{CONTENT}}|$CONTENT|" \
    --expression "s|{{REPOSITORY}}|$1|" \
    --expression "s|{{FILES}}|$FILES|" \
    --expression "s|{{MD5}}|$MD5|" \
    ~/.config/github-split/install.sh.tpl \
    > install.sh

mv $TEMP $CWD/split-$1
info created split-$1

rm --force --recursive $TEMP
