#!/bin/bash
set -e

usage() { echo 'usage: github-split <file> [repository]'; exit; }

log() { echo -e "\033[1;4;32m${1}\033[0m \033[1;33m${@:2}\033[0m"; }
err() { echo -e "\033[1;4;31m${1}\033[0m \033[1;36m${@:2}\033[0m"; }

[[ $1 == '-h' || $1 == '--help' || -z $1 || ! -f $1 ]] && { usage; }
[[ -n $2 ]] && REPOSITORY=$2 || REPOSITORY=$1;
[[ -d split-$REPOSITORY ]] && { err abort split-$REPOSITORY already exists; exit; }

MD5=$(md5sum $1 | cut -d ' ' -f 1)
CHMOD=$(stat --format '%a' $1)

CWD=$(pwd)
TEMP=$(mktemp --directory)

SIZE=$(du $1 | sed 's|[^0-9].*$||g')
BYTES=500KB
[[ $SIZE -gt 5120 ]] && BYTES=1MB;
[[ $SIZE -gt 10240 ]] && BYTES=2MB; 
[[ $SIZE -gt 15360 ]] && BYTES=3MB;
[[ $SIZE -gt 20480 ]] && BYTES=4MB;
[[ $SIZE -gt 25600 ]] && BYTES=5MB;

log split $1 into pieces of $BYTES
cd $TEMP
split --bytes=$BYTES "$CWD/$1"
FILES=$(ls -1 | tr '\n' ' ')
FILES=${FILES::-1}

log create README.md
cat > README.md << EOF
$(echo "## $1")

### curl

\`\`\`bash
curl raw.github.com/jeromedecoster/$REPOSITORY/master/script.sh \\
    --location \\
    --silent \\
    | bash
\`\`\`

### wget

\`\`\`bash
wget raw.github.com/jeromedecoster/$REPOSITORY/master/script.sh \\
    --output-document=- \\
    --quiet \\
    | bash
\`\`\`
EOF

log create script.sh
cat > script.sh << EOF
set -e

URL=https://raw.githubusercontent.com/jeromedecoster/$REPOSITORY/master
FILES=($FILES)
NAME=$1
MD5=$MD5
CHMOD=$CHMOD

log() { echo -e "\033[0;4m\${1}\033[0m \${@:2}"; }

[[ -f \$NAME ]] && { log abort \$NAME already exists; exit; }

CWD=\$(pwd)
TEMP=\$(mktemp --directory)

cd \$TEMP
for file in "\${FILES[@]}"
do
    log download \$URL/\$file
    if [[ -n \$(which curl) ]]
    then
        curl \$URL/\$file \\
            --location \\
            --remote-name \\
            --progress-bar
    else
        wget \$URL/\$file \\
            --quiet \\
            --show-progress
    fi
done

log merge xa*
cat xa* > \$NAME

if [[ \$(md5sum \$NAME | cut -d ' ' -f 1) != \$MD5 ]]
then
    log checksum error
fi

chmod \$CHMOD \$NAME

# check if \$CWD is writable by the user
if [[ -z \$(sudo --user \$(whoami) --set-home bash -c "[[ -w \$CWD ]] && echo 1;") ]]
then
    log warn sudo access is required
    sudo mv \$NAME \$CWD
else
    mv \$NAME \$CWD
fi

log complete \$NAME successfully created

rm --force --recursive \$TEMP
EOF

mv $TEMP $CWD/split-$REPOSITORY
log complete $NAME successfully created

rm --force --recursive $TEMP
